image: ubntintrepid/izanami:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  SCCACHE_DIR: $CI_PROJECT_DIR/.cache

cache:
  key: izanami-cache-key
  paths:
    - $CARGO_HOME/registry/
    - $SCCACHE_DIR

stages:
  - check
  - test
  - deploy

lint:
  stage: check
  before_script:
    - rustup component add rustfmt clippy
  script:
    - cargo fmt -- --check
    - cargo clippy --all --all-targets
    - cargo clippy -p izanami --all-features --all-targets

test:
  stage: test
  script:
    - cargo test --all

pages:
  stage: deploy
  only:
    - master
  script:
    - rm -rf target/doc
    - cargo doc --no-deps -p izanami-service
    - cargo doc --no-deps --all-features
    - rm -rf public && mv target/doc/ public
    - rm -f public/.lock
    - echo '<meta http-equiv="refresh" content="0;URL=izanami/index.html">' > public/index.html
  artifacts:
    paths:
      - public
