dist: xenial
language: rust
cache:
  apt: true
  cargo: true
addons:
  apt:
    packages:
      - libssl-dev
branches:
  only:
    - master

script:
  - cargo test -p izanami-service
  - cargo test -p izanami --all-features

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:      
    - rust: 1.31.1
    - rust: beta
    - rust: nightly
    
    - rust: stable
      before_script:
        - rustup component add rustfmt clippy
      script:
        - cargo fmt -- --check
        - cargo clippy --all --all-targets
        - cargo clippy -p izanami --all-features --all-targets
        - cargo test -p izanami-service
        - cargo test -p izanami --all-features
      before_deploy: >-
        rm -rf target/doc &&
        cargo doc --no-deps -p izanami-service &&
        cargo doc --no-deps -p izanami --all-features &&
        rm -f target/doc/.lock &&
        (echo '<meta http-equiv="refresh" content="0;URL=izanami/index.html">' > target/doc/index.html)
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: ubnt-intrepid/izanami
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
