dist: xenial
language: rust
cache:
  apt: true
  cargo: true
addons:
  apt:
    packages:
      - libssl-dev
branches:
  only:
    - master

script: .ci/run-test.sh

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:      
    - rust: stable
      before_script:
        - rustup component add rustfmt clippy
      before_deploy: >-
        rm -rf target/doc &&
        .ci/build-doc.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: ubnt-intrepid/izanami
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
    - rust: 1.31.1
    - rust: beta
    - rust: nightly
