resources:
  containers:
    - container: tarpaulin
      image: xd009642/tarpaulin:latest
      options: --security-opt seccomp=unconfined

variables:
  CARGO_TERM_VERBOSE: true

jobs:
- template: .ci/jobs/test.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
    # variables:
    #   OPENSSL_DIR: C:\OpenSSL
    #   OPENSSL_VERSION: 1_1_0j
    # before_script:
    # - script: |
    #     mkdir %OPENSSL_DIR%
    #     curl -sSfO http://slproweb.com/download/Win64OpenSSL-%OPENSSL_VERSION%.exe
    #     Win64OpenSSL-%OPENSSL_VERSION%.exe /SILENT /VERYSILENT /SP- /DIR=%OPENSSL_DIR%
    #   displayName: 'install OpenSSL'

- template: .ci/jobs/test.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.13'

- template: .ci/jobs/test.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        stable:
          rust_toolchain: stable
        beta:
          rust_toolchain: beta
        nightly:
          rust_toolchain: nightly
        minimum_supported:
          rust_toolchain: 1.32.0
    after_script:
    - bash: .ci/scripts/build-doc.sh
      displayName: 'build API doc'
    - bash: .ci/scripts/deploy-doc.sh
      displayName: 'deploy API doc on GitHub Pages'
      condition: and(succeeded(), eq(variables['rust_toolchain'], 'stable'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      env:
        GH_TOKEN: $(myGitHubToken)

- job: coverage
  pool:
    vmImage: 'ubuntu-16.04'
  container: tarpaulin
  steps:
  - script: |
      rustup --version
      rustc --version
      cargo --version
      cargo tarpaulin --version
    displayName: 'show toolchain version'
  - bash: .ci/scripts/run-coverage-test.sh
    displayName: 'run coverage test'
    env:
      CODECOV_TOKEN: $(myCodecovToken)
