[package]
name = "izanami"
description = "An HTTP server implementation powered by hyper and tower-service."
version = "0.1.0-preview.2"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ubnt-intrepid/izanami.git"
readme = "README.md"

include = [
  "/Cargo.toml",
  "/src/**/*.rs",
  "/tests/**/*.rs",
]

[dependencies]
izanami-http = { version = "0.1.0-preview.1", path = "izanami-http" }
izanami-service = { version = "0.1.0-preview.1", path = "izanami-service" }
izanami-util = { version = "0.1.0-preview.1", path = "izanami-util" }

bytes = "0.4"
failure = "0.1.3"
futures = "0.1"
h2 = "0.1"
http = "0.1"
httpdate = "0.3"
hyper = "0.12"
log = "0.4"
tokio = { version = "0.1.15", features = ["sync"] }
tokio-buf = "0.1"
tokio-executor = "0.1"
tokio-threadpool = "0.1"

[dev-dependencies]
http = "0.1"
tempfile = "3"
version-sync = "0.7"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[workspace]
members = [
  "izanami-http",
  "izanami-service",
  "izanami-util",

  # SSL/TLS support (not available)
  "izanami-tls",
  "izanami-openssl",
  "izanami-rustls",
]
