[package]
name = "izanami"
version = "0.1.0-preview.2"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ubnt-intrepid/izanami.git"
readme = "README.md"
description = "An HTTP server implementation powered by hyper and tower-service."

include = [
  "/Cargo.toml",
  "/src/**/*.rs",
  "/tests/**/*.rs",
]

[dependencies]
izanami-rt = { version = "0.1.0-preview.1", path = "izanami-rt" }
izanami-service = { version = "0.1.0-preview.1", path = "izanami-service" }
izanami-util = { version = "0.1.0-preview.1", path = "izanami-util" }

bytes = "0.4"
failure = "0.1.3"
futures = "0.1"
http = "0.1"
hyper = "0.12"
log = "0.4"
tokio = { version = "0.1.15", features = ["sync"] }
tokio-executor = "0.1"
tokio-io = "0.1"

native-tls = { version = "0.2", optional = true }
tokio-tls = { version = "0.2", optional = true }

rustls = { version = "0.14", optional = true }
tokio-rustls = { version = "0.8", optional = true }

openssl = { version = "0.10", optional = true }
tokio-openssl = { version = "0.3", optional = true }

[dev-dependencies]
tempfile = "3"
version-sync = "0.7"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[features]
use-native-tls = ["native-tls", "tokio-tls"]
use-rustls = ["rustls", "tokio-rustls"]
use-openssl = ["openssl", "tokio-openssl"]

[workspace]
members = [
  "izanami-rt",
  "izanami-service",
  "izanami-util",

  "examples/echo-service",
  "examples/native-tls-server",
  "examples/openssl-server",
  "examples/rustls-server",
  "examples/tcp-server",
  "examples/unix-server",
]
