(function() {var implementors = {};
implementors["izanami_examples"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"izanami_examples/struct.Hello.html\" title=\"struct izanami_examples::Hello\">Hello</a>",synthetic:true,types:["izanami_examples::Hello"]},];
implementors["izanami_h2"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"izanami_h2/struct.Server.html\" title=\"struct izanami_h2::Server\">Server</a>",synthetic:true,types:["izanami_h2::Server"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"izanami_h2/struct.Events.html\" title=\"struct izanami_h2::Events\">Events</a>&lt;'a&gt;",synthetic:true,types:["izanami_h2::Events"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"izanami_h2/struct.Data.html\" title=\"struct izanami_h2::Data\">Data</a>",synthetic:true,types:["izanami_h2::Data"]},];
implementors["izanami_hyper"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"izanami_hyper/struct.Server.html\" title=\"struct izanami_hyper::Server\">Server</a>",synthetic:true,types:["izanami_hyper::Server"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"izanami_hyper/struct.Events.html\" title=\"struct izanami_hyper::Events\">Events</a>&lt;'a&gt;",synthetic:true,types:["izanami_hyper::Events"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()